# Generated by Django 4.0.4 on 2022-06-17 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_remove_profile_dailyroutine'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dailyRoutine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dailyRoutine', to='webapi.routine'),
            preserve_default=False,
        ),
    ]
