# Generated by Django 4.0.4 on 2022-06-18 18:21

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0004_alter_profile_dailyroutine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dailyRoutine',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dailyRoutine', to='webapi.routine'),
        ),
    ]
