# Generated by Django 4.0.4 on 2022-06-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0006_alter_profile_dailyroutine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dailyRoutine',
        ),
        migrations.AddField(
            model_name='profile',
            name='diet',
            field=models.TextField(default='No Specified Diet'),
        ),
        migrations.AddField(
            model_name='profile',
            name='maintained',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='steps',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Routine',
        ),
    ]
